import { useToast } from "@chakra-ui/react";
import FullPageLoadingSpinner from "@components/shared/FullPageLoadingSpinner";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { useAuthState } from "react-firebase-hooks/auth";
import { auth } from "../../firebase";

const OnlyVerifiedEmail = ({ children }) => {
	const toast = useToast();
	const router = useRouter();
	const [currentUser] = useAuthState(auth);

	useEffect(() => {});

	if (!currentUser) {
		router.push("/");
		return <FullPageLoadingSpinner />;
	}

	if (!currentUser?.emailVerified) {
		router.replace("/auth/verifyemail").then(() => {
			//! The last page (from which the push is being called) re-renders while router.push is being used.
			//! Unwanted Error and Warning are generated by these toast on re-render.
			if (!toast.isActive("email-not-verified")) {
				toast({
					id: "email-not-verified",
					title: "Your email is not verified.",
					description: "Please verify your email to continue.",
					status: "warning",
					duration: 9000,
					isClosable: true,
				});
			}
		});
		return <FullPageLoadingSpinner />;
	}

	return <>{children}</>;
};

export default OnlyVerifiedEmail;
